### ISSUE TITLE
Estratégias de modelagem da base

### ISSUE THREAD

**Issue by fjuniorr** [splor-mg/dados-sigplan-monitoramento#1]
Dúvida da Vivi no Teams:

> Pessoal, bom dia, tudo bem?
> Eu vou colocar uma dúvida aqui, mas como sei que estão tomados com muitos projetos, pode ser quando tiverem uma brecha mesmo.
> Sobre esta transformação de dados, eu estou trabalhando com a base do 6º bimestre. Ai nela, na parte de valores, que seriam as colunas que serão convertidas em linhas, eu tenho mais de um atributo envolvido.
> Exemplo:
> Eu tenho coluna de:
> Previsão na LOA
> Programação Inicial (Orçamentaria) cada coluna um mes diferente
> Despesa Realizada (Orçamentária) cada coluna um mês diferente
> Despesa Realizada de Pessoal (Orçamentaria) cada coluna um mes diferente
> Meta Fisica Programada
> Meta Fisica Realizada, cada coluna um mes diferente
>  
> Ai minha duvida, que se eu selecionar todas e transformar linhas em colunas, eu vou ter uma coluna unica com todos estes atributos distintos e uma outra coluna com seus valores correspondentes, mas acho que seria mais adequado, cada coluna refletir um unico atributo, assim, se tenho 6 atributos, eu teria 12 colunas (Coluna atributo e Coluna Valor).
> Só que ficam as duvidas:
> 1) Se meu entendimento estiver correto, o melhor caminho seria selecionar apenas as colunas do atributo e transformar e ir fazendo atributo por atributo ate gerar as 12 colunas? Ou isso poderia gerar algum tipo de duplicidade ou inconsistencia na base?
> 2) O melhor caminho seria dividir esta base gigante em outras (Exemplo, base monitoramento meta fisica, base monitoramento meta orçamentaria, base monitoramento previsao inicial) e transformar os dados em cada uma e depois linkar as bases
> Ou ainda outro caminho?

**Comment by labanca** [comment]
O processo foi explicado de acordo com o descrito em https://github.com/splor-mg/painel-planejamento-orcamento/issues/6#issuecomment-1894536419 e também os problemas de repetição de nomes e valores após o pivot passivo das colunas totais das bases.

As abordagens possíveis para a questão dos valores duplicados das colunas totais foram:

1 - A base está validada, então os valores das colunas totais correspondem aos valores das colunas mensais. Então as colunas totais podem ser excluídas (ainda não resolve o problema de colunas que referenciam valores anuais, mas não tem relação com as colunas mensais diretamente, como valores programados)
2 - Manter as colunas de totais repetidas, mas quando utilizá-las nos dashboards do powerbi fazer operações adequadas para lidar com essa repetição, como `calculates` ou `max`. Essa abordagem trás dificuldades maiores na hora de construir os relatórios.
3 - Fazer mais transformações na base depois de pivotar as colunas de mesess pivotando também as colunas anuais, tornando o valor do ano também uma coluna nova ou mesmo na mesma coluna do mês. Aqui novamente será necessário filtrar corretamente nos dashboards pra não incluir as linhas de total por ano e duplicar valores. Esse caminho é cheiro de armadilhas já na parte de transformação e pode requerer correções manuais (nem sempre a coluna anual terá o ano ao final de seu nome, por exemplo). 
4 - Retirar as colunas totais dessa base e criar outra base somente com elas (mantendo colunas relevantes como uo, acao, setor, etc.)

Viviane respondeu:

> eu vou neste painel de teste deixar a base crua que to simulando os visuais com totais e simular com a base transformada pra ver se ta dando os mesmos resultados, caso não verifico entao o que seria melhor de usar, dentro das opções 2 e 3 que me mandou.
Com eu estou construindo o painel de teste, com as bases de 2022 e o RIM de 2022 já existe em pdf eu consigo ir conferindo se o resultado dos visuais bate com o relatorio publicado e ver se os numeros estão corretos para cada visual de acordo com o gráfico/tabela do relatorio publicado.

**Comment by fjuniorr** [comment]
Acho que podemos considerar esse issue finalizado, mais é outro exemplo de caso de uso em que seria útil fazer transformações mais agressivas durante o make transform/build para aumentar a facilidade de uso das bases.
